name: React Project Action
on: push


jobs: 
    Deploment:
        runs-on: ubuntu:latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: installing depencies
              run: npm ci
            - name: build project
              run: npm run 
            - name: deployment
              run: echo "deploying code..."   
              