name: React Project Action
on: push

jobs: 
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: installing dependencies
        run: npm ci

      - name: build project
        run: npm run build

      - name: deployment
        run: echo "deploying code..."
      - name: getting meta data about github
        run: echo "${{toJson(github)}}"